"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowUp, ArrowUpRight, Check, Copy, Menu, X, Trophy, Code2, Building2, Layers, FileText, Users, GitBranch, Code2 as Github, CalendarDays } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import VueCraft from "@/components/vue-craft";
import Hero from "@/components/hero";
import { PokemonHabitat, ThemeSelector } from "@/components/pokemon-theme";
import { useScrollReveal } from "@/hooks/use-scroll-reveal";

const projects = [
  { id: "performance", number: "01", category: "Performance management", title: "SPMS · From targets to impact", short: "Office goals and individual contributions, connected through one clear performance workflow.", description: "A Strategic Performance Management System for Office and Individual Performance Commitment and Review (OPCR/IPCR). It connects target setting, cascading responsibilities, reporting, and evaluation.", tags: ["Laravel", "Vue + Inertia", "Workflow engine"], features: ["Cascade office targets into individual commitments and assign personnel to indicators.", "Bring monthly accomplishments, supporting attachments, and ratings into one workspace.", "Guide plans through negotiation, review, and approval with clear edit permissions.", "Keep midyear and final evaluations separate, with role-based dashboards and reporting."], note: "TESDA enterprise project. This portfolio uses illustrative interface previews; internal records and production access are not published." },
  { id: "recruitment", number: "02", category: "Talent acquisition", title: "RSP · A clearer path to hiring", short: "Recruitment, selection, and placement—from the first application to committee review.", description: "A recruitment platform supporting job postings, applicant profiles, screening against Civil Service Qualification Standards, and committee evaluations.", tags: ["Laravel", "Qualification standards", "Role-based access"], features: ["Organize vacancies, applicant information, and submitted requirements.", "Support screening against education, experience, training, and eligibility requirements.", "Give reviewers the context they need for consistent committee evaluations.", "Keep access and workflow actions aligned with each user's role."], note: "TESDA enterprise project. Candidate names and statuses in the preview are illustrative." },
  { id: "records", number: "03", category: "Document automation", title: "PDS · Precision in every field", short: "Structured employee information, transformed into consistent Civil Service documents.", description: "An automated Personal Data Sheet generator for CS Form No. 212, with work experience sheets and standardized employee records.", tags: ["PHP + Laravel", "PDF generation", "Vue"], features: ["Organize personal, educational, family, and employment information.", "Render structured records into the official form layout.", "Generate the supporting Work Experience Sheet.", "Reduce repeated manual encoding across employee documents."], note: "The preview is a simplified illustration of the document layout, not an official downloadable form." },
  { id: "hris", number: "04", category: "People & operations", title: "HRIS · People, brought together", short: "A connected foundation for personnel records and the everyday work of human resources.", description: "An enterprise HRIS suite bringing employee information and personnel workflows into a connected system for agency operations.", tags: ["Laravel", "Vue + Inertia", "MySQL"], features: ["Bring employee profiles and digital 201 records together.", "Support leave management and attendance integration.", "Organize personnel movement and employee information workflows.", "Give authorized staff a consistent view of the information they manage."], note: "TESDA enterprise project. The preview is an interface illustration with sample content." },
] as const;
const milestones = [
  { year: "2019", icon: Trophy, title: "WorldSkills Kazan", text: "Represented Team Philippines in Web Technologies at the 45th WorldSkills Competition in Kazan, Russia.", type: "THE GLOBAL STAGE" },
  { year: "2020", icon: Building2, title: "Building for the public sector", text: "Joined TESDA, working on the systems behind human resources and everyday agency operations.", type: "TESDA · PHILIPPINES" },
  { year: "2022", icon: Code2, title: "A more connected stack", text: "Brought Laravel, Vue, and Inertia together to build reactive interfaces on a reliable backend.", type: "STACK MODERNIZATION" },
  { year: "2024—now", icon: Layers, title: "From features to complete systems", text: "Developing performance management, recruitment, and personnel platforms for agency-wide use.", type: "ENTERPRISE ENGINEERING" },
];
function InterfacePreview({ type }: { type: string }) {
  if (type === "records") return <div className="paper-preview" aria-hidden="true"><div className="paper-eyebrow">CS FORM NO. 212 · REVISED 2017</div><h3>PERSONAL DATA SHEET</h3><div className="paper-section">I. PERSONAL INFORMATION</div>{["SURNAME", "FIRST NAME", "MIDDLE NAME", "DATE OF BIRTH", "RESIDENTIAL ADDRESS"].map(label => <div className="paper-row" key={label}><span>{label}</span><span><i className="paper-line" /></span></div>)}</div>;
  return <div className={`mini-app ${type !== "performance" ? "recruit" : ""}`} aria-hidden="true"><div className="mini-app-header"><strong><span className="mini-logo"><Layers size={13} /></span>{type === "performance" ? "prime / performance" : type === "recruitment" ? "careers / recruitment" : "prime / people"}</strong><span>TESDA</span></div><div className="mini-app-body">
    {type === "performance" ? <><div className="mini-app-title">Office performance</div><div className="mini-subtitle">Commitments, accomplishments & review</div><div className="mini-stat-grid"><div className="mini-stat"><strong>OPCR</strong><span>Office commitments</span></div><div className="mini-stat"><strong>IPCR</strong><span>Individual commitments</span></div><div className="mini-stat"><strong>2026</strong><span>Performance cycle</span></div></div>{["System development", "Technical assistance", "Process improvement"].map((t,i)=><div className="mini-row" key={t}><span>{t}</span><span className="mini-bar"><i style={{width:`${[82,65,94][i]}%`}} /></span><span className={`mini-badge ${i===1?"amber":""}`}>{i===1?"In progress":"For review"}</span></div>)}</> : type === "recruitment" ? <><div className="mini-app-title">The right people. The next chapter.</div><div className="mini-subtitle">Recruitment, selection & placement</div><div className="mini-tabs"><span>Applications</span><span>Vacancies</span><span>Evaluation</span></div>{[["AM","Applicant profile","For screening"],["JL","Application requirements","In review"],["RC","Qualification standards","Verified"]].map(([initial,title,status],i)=><div className="mini-row" key={initial}><div className="candidate">{initial}</div><span>{title}</span><span className={`mini-badge ${i===0?"lavender":i===1?"amber":""}`}>{status}</span></div>)}</> : <><div className="mini-app-title">Everything your people need.</div><div className="personnel-summary"><div className="personnel-avatar">AC</div><div><strong>Employee workspace</strong><p>One profile. Connected records.</p></div></div><div className="personnel-cards"><div><Users size={17}/>Employee profile</div><div><FileText size={17}/>201 records</div><div><CalendarDays size={17}/>Leave management</div><div><GitBranch size={17}/>Personnel movement</div></div></>}
    <div className="mock-caption">ILLUSTRATIVE INTERFACE</div></div></div>;
}
function ProjectCard({ project }: { project: typeof projects[number] }) {
  return <article className="project-card"><div className={`project-visual ${project.id}`}><div className="visual-top"><span className="visual-label"><span className="project-index">{project.number}</span>{project.category}</span>{project.id==="records"?<FileText/>:project.id==="recruitment"?<Users/>:project.id==="hris"?<Building2/>:<Layers/>}</div><InterfacePreview type={project.id}/></div><div className="project-info"><div><div className="project-category">{project.category}</div><h3>{project.title}</h3><p>{project.short}</p></div><Dialog><DialogTrigger asChild><button className="project-button" aria-label={`View ${project.title}`}><ArrowUpRight size={21}/></button></DialogTrigger><DialogContent className="project-dialog"><div className="dialog-kicker">Selected work / {project.number}</div><DialogTitle>{project.title}</DialogTitle><DialogDescription>{project.description}</DialogDescription><div className="dialog-content"><h4>What the system supports</h4><ul>{project.features.map(feature=><li key={feature}><Check/>{feature}</li>)}</ul></div><div className="project-tags">{project.tags.map(tag=><span className="tag" key={tag}>{tag}</span>)}</div><p className="dialog-note">{project.note}</p><a className="text-link" href="mailto:suppmon27@gmail.com">Let’s talk about this work <ArrowUpRight size={17}/></a></DialogContent></Dialog></div><div className="project-tags">{project.tags.map(tag=><span className="tag" key={tag}>{tag}</span>)}</div></article>;
}
export default function Portfolio() {
  const revealRef = useScrollReveal();
  const [menuOpen,setMenuOpen] = useState(false);
  const [active,setActive] = useState("about");
  const [copyState,setCopyState] = useState<"idle"|"copied"|"failed">("idle");
  const copyTimer = useRef<ReturnType<typeof setTimeout>|null>(null);
  const menuButton = useRef<HTMLButtonElement>(null);
  useEffect(()=>{const sections=document.querySelectorAll("main section[id]");const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)setActive(entry.target.id);});},{rootMargin:"-20% 0px -60% 0px",threshold:0});sections.forEach(section=>observer.observe(section));return()=>{observer.disconnect();if(copyTimer.current)clearTimeout(copyTimer.current);};},[]);
  useEffect(()=>{if(!menuOpen)return;const close=(e:KeyboardEvent)=>{if(e.key==="Escape"){setMenuOpen(false);menuButton.current?.focus();}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[menuOpen]);
  async function copyEmail(){try{await navigator.clipboard.writeText("suppmon27@gmail.com");setCopyState("copied");}catch{setCopyState("failed");}if(copyTimer.current)clearTimeout(copyTimer.current);copyTimer.current=setTimeout(()=>setCopyState("idle"),3000);}
  const links=[["about","About"],["projects","Selected work"],["timeline","Journey"],["craft-hobbies","Beyond code"]];
  return <div className="portfolio-page"><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><nav className="shell nav" aria-label="Main navigation"><a className="wordmark" href="#about" aria-label="Mon — back to top"><strong>mon<span>.</span></strong><span className="brand-caption">ANTHONY CABIGAYAN<br/>SOFTWARE ENGINEER</span></a><button className="menu-toggle" ref={menuButton} aria-label={menuOpen?"Close menu":"Open menu"} aria-expanded={menuOpen} aria-controls="site-navigation" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X size={22}/>:<Menu size={22}/>}</button><div id="site-navigation" className={`nav-links ${menuOpen?"open":""}`}>{links.map(([id,label])=><a className={active===id?"active":""} key={id} href={`#${id}`} onClick={()=>setMenuOpen(false)} aria-current={active===id?"location":undefined}>{label}</a>)}<a href="/cv" onClick={()=>setMenuOpen(false)}>CV Studio</a><a className="nav-contact" href="#contact" onClick={()=>setMenuOpen(false)}>Let’s talk <ArrowUpRight size={16}/></a></div><ThemeSelector/></nav></header><PokemonHabitat/>
  <main id="main" ref={revealRef}><Hero/>
  <div className="tech-strip"><div className="shell"><span className="tech-label">TOOLS OF<br/>THE TRADE</span>{[["◇","Laravel"],["∨","Vue.js"],["↗","Inertia.js"],["⌘","React"],["N","Next.js"],["▱","Docker"]].map(([symbol,label])=><span className="tech-item" key={label}><span aria-hidden="true" className="tech-symbol">{symbol}</span>{label}</span>)}</div></div>
  <section id="projects" className="shell section"><div className="section-heading"><div><div className="eyebrow"><span className="short-line"/>01 / SELECTED WORK</div><h2>Real workflows.<br/><span>Thoughtful solutions.</span></h2></div><p>A selection of enterprise systems built to simplify operations and support the people behind public service.</p></div><div className="project-grid">{projects.map(project=><ProjectCard key={project.id} project={project}/>)}</div></section>
  <div className="shell about-band"><div><div className="eyebrow"><span className="short-line"/>THE WAY I BUILD</div><h2>Good software starts<br/>with understanding.</h2></div><p>From the first conversation to the final deployment, I care about how a system fits into someone’s day. My focus is simple: <strong>clear interfaces, dependable foundations, and workflows that make sense.</strong> That’s the thread connecting my work across Laravel, Vue, and enterprise systems.</p></div>
  <section id="timeline" className="shell section"><div className="section-heading"><div><div className="eyebrow"><span className="short-line"/>02 / THE JOURNEY</div><h2>Always building. <span>Always learning.</span></h2></div></div><div className="timeline">{milestones.map(({year,icon:Icon,title,text,type})=><article className="timeline-row" key={year}><span className="timeline-year">{year}</span><span className="timeline-icon"><Icon/></span><div><h3>{title}</h3><p>{text}</p></div><span className="timeline-type">{type}</span></article>)}</div></section>
  <section id="craft-hobbies" className="shell section craft-section"><div className="craft-layout"><div className="craft-intro"><div className="eyebrow"><span className="short-line"/>03 / BEYOND THE TERMINAL</div><h2>Curiosity doesn’t<br/>clock out.</h2><p>New places, long runs, anime, and the small experiments that keep me curious.</p></div><VueCraft/></div></section>
  <section id="contact" className="shell contact-section"><div className="eyebrow"><span className="short-line"/>04 / START A CONVERSATION</div><div className="contact-top"><h2>Something in mind?<br/><span>Let’s build it.</span></h2><a className="contact-orbit" href="mailto:suppmon27@gmail.com" aria-label="Email Anthony Cabigayan"><ArrowUpRight/></a></div><div className="contact-bottom"><p>Open to thoughtful collaborations, enterprise projects, and conversations about what comes next.</p><div className="contact-links"><div className="email-group"><a href="mailto:suppmon27@gmail.com">suppmon27@gmail.com</a><button className="copy-button" onClick={copyEmail} aria-label={copyState==="copied"?"Email copied":"Copy email address"}>{copyState==="copied"?<Check size={14}/>:<Copy size={14}/>}</button><span className="copy-feedback" role="status">{copyState==="copied"?"Copied":copyState==="failed"?"Select the address to copy":""}</span></div><a className="text-link" href="https://github.com/monqzxc" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={16}/></a></div></div></section></main>
  <footer className="footer"><div className="shell"><div className="footer-left"><span className="footer-mark">mon.</span><p>© {new Date().getFullYear()} Anthony Cabigayan</p></div><div className="footer-right"><span>Thoughtfully built in the Philippines.</span><a href="#about">Back to top <ArrowUp size={14}/></a></div></div></footer></div>;
}
